import type { ThemeConfig } from "antd";
import { COLORS } from "../../tailwind.config";

export const theme: ThemeConfig = {
  token: {
    colorPrimary: COLORS.primary.DEFAULT,
    colorBgLayout: "#fff",
    fontFamily: "Inter, sans-serif",
    colorSuccess: COLORS.success.DEFAULT,
    colorSuccessHover: COLORS.success.hover,
    colorError: COLORS.error.DEFAULT,
    colorErrorHover: COLORS.error.hover,
    colorWarning: COLORS.warning.DEFAULT,
    colorWarningHover: COLORS.warning.hover,
  },
  components: {
    Menu: {
      iconSize: 20,
      iconMarginInlineEnd: 18,
    },
    Button: {
      colorPrimaryBg: COLORS.primary.DEFAULT,
      colorPrimaryBgHover: COLORS.primary.hover,
      borderRadius: 12,
      borderRadiusLG: 12,
      borderRadiusSM: 12,
      borderRadiusXS: 12,
      fontWeight: 500,
      boxShadow: "0 0",
      paddingInline: 20.5,
      paddingInlineLG: 20.5,
      paddingInlineSM: 20.5,
      fontSizeXL: 16,
      fontSizeLG: 16,
      fontSizeSM: 14,
      fontSize: 14,
      controlHeightLG: 48,
      controlHeight: 42,
      controlHeightSM: 36,
      controlHeightXS: 29,
      defaultBorderColor: COLORS.primary[93],
      ghostBg: COLORS.primary[93],
    },
    Input: {
      activeBorderColor: COLORS.primary[80],
      colorErrorBorder: COLORS.error[70],
      colorWarningBorder: COLORS.warning.DEFAULT,
      colorBorder: COLORS.primary[93],
      colorBorderBg: COLORS.primary[93],
      hoverBorderColor: COLORS.primary[90],
      borderRadiusLG: 12,
      borderRadius: 12,
      borderRadiusSM: 12,
      fontSizeLG: 16,
      fontSize: 14,
      fontSizeSM: 14,
      paddingBlockLG: 11.5,
      paddingInlineLG: 11,
      paddingBlock: 15.5,
      paddingInline: 12,
      paddingBlockSM: 13.5,
      paddingInlineSM: 14,
      lineHeight: 1,
      lineHeightSM: 1,
    },
    Typography: {
      fontSizeHeading1: 30,
      fontSizeHeading2: 27,
      fontSizeHeading3: 22,
      fontSizeHeading4: 20,
      fontSizeHeading5: 18,
      lineHeightHeading1: 38 / 30,
      lineHeightHeading2: 30 / 24,
      lineHeightHeading3: 27 / 22,
      lineHeightHeading4: 24 / 20,
      lineHeightHeading5: 22 / 18,
    },
    Divider: {
      verticalMarginInline: 0,
      colorBgBase: COLORS.neutral[90],
    },
    Badge: {
      colorSuccess: COLORS.success.DEFAULT,
      colorSuccessHover: COLORS.success.hover,
      colorError: COLORS.error.DEFAULT,
      colorErrorHover: COLORS.error.hover,
      colorWarning: COLORS.warning.DEFAULT,
      colorWarningHover: COLORS.warning.hover,
      colorBorder: "transparent",
      colorBorderBg: "transparent",
    },
    DatePicker: {
      activeBorderColor: COLORS.primary[80],
      colorErrorBorder: COLORS.error[70],
      colorWarningBorder: COLORS.warning.DEFAULT,
      colorBorder: COLORS.primary[93],
      colorBorderBg: COLORS.primary[93],
      hoverBorderColor: COLORS.primary[90],
      borderRadiusLG: 12,
      borderRadius: 12,
      borderRadiusSM: 12,
      fontSizeLG: 16,
      fontSize: 14,
      fontSizeSM: 14,
      paddingBlockLG: 11.5,
      paddingInlineLG: 11,
      paddingBlock: 12,
      paddingInline: 12,
      paddingBlockSM: 3,
      paddingInlineSM: 7,
      controlHeight: 48,
      controlHeightLG: 49,
      controlHeightSM: 30,
    },
    Select: {
      activeBorderColor: COLORS.primary[80],
      colorErrorBorder: COLORS.error[70],
      colorWarningBorder: COLORS.warning.DEFAULT,
      colorBorder: COLORS.primary[93],
      colorBorderBg: COLORS.primary[93],
      hoverBorderColor: COLORS.primary[90],
      borderRadiusLG: 12,
      borderRadius: 12,
      borderRadiusSM: 12,
      fontSizeLG: 14,
      fontSize: 14,
      fontSizeSM: 14,
      controlHeight: 51.8,
      controlHeightLG: 62,
      controlHeightSM: 30,
      paddingContentVertical: 12,
      optionSelectedBg: COLORS.primary[90],
    },
    Table: {
      headerBg: COLORS.primary.DEFAULT,
      headerColor: "#fff",
      headerBorderRadius: 12,
      fontSizeHeading1: 600,
      headerSortHoverBg: COLORS.primary[70],
      bodySortBg: "transparent",
      headerSortActiveBg: COLORS.primary[50],
      cellPaddingBlock: 12,
      cellPaddingInline: 12,
      rowSelectedBg: "#EEEEF0",
    },
    Modal: {
      borderRadius: 20,
    },
    Card: {
      paddingSM: 16,
      borderRadius: 20,
    },
  },
};
